apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
{{- if .Values.ingress.alb }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP": 80 }, { "HTTPS": 443 }]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:563149050413:certificate/03fee5ef-ee20-4320-9a8f-530386ad795d
    alb.ingress.kubernetes.io/ssl-redirect: "443"
{{- end }}
spec:
{{- if .Values.ingress.alb }}
  ingressClassName: alb
{{- end }}
  rules:
    - host: {{ if .Values.ingress.alb }} jobster-backend.com {{ else }} jobster.local {{ end }}
      http:
        paths:
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: jobs-http
                port:
                  number: {{ .Values.jobs.port.http }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-http
                port:
                  number: {{ .Values.auth.port.http }}